(part "BME688"
    (packageRef "BME688")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CSB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SDI") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCK") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDDIO") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "BOSCH")
    (property "Manufacturer_Part_Number" "BME688")
    (property "Mouser_Part_Number" "262-BME688")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bosch-Sensortec/BME688?qs=IS%252B4QmGtzzqQoVDscqwx3A%3D%3D")
    (property "Arrow_Part_Number" "BME688")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bme688/bosch-sensortec?utm_currency=USD&region=nac")
    (property "Description" "Gas sensor measuring relative humidity, barometric pressure, ambient temperature and gas (VOC)")
    (property "Datasheet_Link" "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme688-ds000.pdf")
    (property "symbolName1" "BME688")
)
