(part "L-KLS1-TF-003-H1_85-R"
    (packageRef "L-KLS1-TF-003-H1_85-R")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "G_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "G_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "G_3") (portType INOUT))
        (port "13" (symbPinId 13) (portName "G_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "KLS Electronic")
    (property "Manufacturer_Part_Number" "L-KLS1-TF-003-H1.85-R")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Micro SD Card Connector")
    (property "Datasheet_Link" "https://img.ozdisan.com/ETicaret_Dosya/476392_7149645.pdf")
    (property "symbolName1" "L-KLS1-TF-003-H1_85-R")
)
